spring:
  datasource:
    #driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/runescape_application
    username: postgres
    password: parkour14
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    
Tyler:
  url: 
  loaders: 
  reports:
  outputFileLocation: C:\Users\Tyler\Documents\Coding\Outputs\Spring\Runescape-App\

---

spring:
  profiles: load-items
Tyler: 
  loaders: loadItems
  url: https://rsbuddy.com/exchange/summary.json

---

spring:
  profiles: load-price-data
Tyler:
  loaders: loadPriceData
  url: https://api.rsbuddy.com/grandExchange?a=guidePrice&i=

---

spring:
  profiles: margin-finder
Tyler:
  reports: marginFinder
  outputFileLocation: C:\Users\Tyler\Documents\Coding\Outputs\Spring\Runescape-App\MarginFinder\
  
    
    
    